apiVersion: v1
kind: Service
metadata:
  name: nginx-k8s-web-hello
spec:
  type: LoadBalancer
  selector:
    app: nginx-k8s-web-hello
  ports:
    - port: 3030
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata: # Deployment key name for resource use
  name: nginx-k8s-web-hello
spec:
  selector: # which pods manged by this deployment
    matchLabels:
      app: nginx-k8s-web-hello
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-k8s-web-hello
    spec:
      containers:
        - name: k8s-web-hello
          image: dotrunghg1999/nginx-k8s-web-hello
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
