apiVersion: apps/v1
kind: Deployment
metadata: # Deployment key name for resource use
  name: my-react-app
spec:
  selector: # which pods manged by this deployment
    matchLabels:
      app: my-react-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-react-app
    spec:
      containers:
        - name: my-react-app
          image: dotrunghg1999/my-react-app
          resources:
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - containerPort: 3000
