# Use an official Node.js runtime as a parent image
FROM node:14-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the React app
RUN npm run build

# Install a simple HTTP server to serve the static files
RUN npm install -g serve

# Set the environment variable to point to the build folder
ENV REACT_APP_ENV=production

# Expose port 3000
EXPOSE 3000

# Run the server command to serve the static files
CMD ["serve", "-s", "build", "-l", "3000"]
